FROM debian:buster-slim

# Installer MongoDB Shell et ses dépendances
RUN apt-get update && apt-get install -y \
    wget gnupg libssl1.1 python3 python3-pip \
    && wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | apt-key add - \
    && echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/debian buster/mongodb-org/5.0 main" > /etc/apt/sources.list.d/mongodb-org-5.0.list \
    && apt-get update && apt-get install -y mongodb-org-shell \
    && apt-get clean

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers de l'application
COPY requirements.txt /app/requirements.txt
COPY app.py /app/app.py

# Installer les dépendances Python
RUN pip3 install --no-cache-dir -r requirements.txt

# Exposer le port Flask
EXPOSE 5000

# Démarrer l'application Flask
CMD ["python3", "app.py"]
