apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-probe-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: cyrinez/webdb-probe:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URL
          value: "mongodb://mongodb-service.czribi.svc.cluster.local:27017/"
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
---

apiVersion: v1
kind: Service
metadata:
  name: webdb-service
spec:
  selector:
    app: webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
