version: "3.8"

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask-app:v1
    container_name: flask-app-v1
    ports:
      - "5000:5000"
    networks:
      - flask-mongo-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb-container-v1
    ports:
      - "27017:27017"
    networks:
      - flask-mongo-network

networks:
  flask-mongo-network:
    driver: bridge
