apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  MONGO_URL: "mongodb://{{ .Values.mongodb.service.name }}:{{ .Values.mongodb.service.port }}/"

