apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webdb.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.webdb.service.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP

