apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: czribi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: cyrinez/flask-app:v1
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m" # 0.1 core
          limits:
            cpu: "500m" # 0.5 core
