apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: challenge11-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: webdb.czribi.net4255.luxbulb.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.webdb.service.name }}
                port:
                  number: {{ .Values.webdb.service.port }}
    - host: webnodb.czribi.net4255.luxbulb.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.webnodb.service.name }}
                port:
                  number: {{ .Values.webnodb.service.port }}
