apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongodb.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.mongodb.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.mongodb.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongodb.service.name }}
    spec:
      containers:
        - name: mongodb
          image: {{ .Values.mongodb.image }}
          ports:
            - containerPort: 27017
          resources:
            requests:
              memory: {{ .Values.mongodb.resources.requests.memory }}
              cpu: {{ .Values.mongodb.resources.requests.cpu }}
            limits:
              memory: {{ .Values.mongodb.resources.limits.memory }}
              cpu: {{ .Values.mongodb.resources.limits.cpu }}
