apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webnodb.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.webnodb.service.name }}
spec:
  selector:
    app: {{ .Values.webnodb.service.name }}
  ports:
  - protocol: TCP
    port: {{ .Values.webnodb.service.port }}
    targetPort: 80
  type: ClusterIP
