apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-script
  namespace: czribi
data:
  init.js: |
    rs.initiate({
      _id: "rs0",
      members: [
        { _id: 0, host: "mongodb-0.mongodb.czribi.svc.cluster.local:27017" },
        { _id: 1, host: "mongodb-1.mongodb.czribi.svc.cluster.local:27017" },
        { _id: 2, host: "mongodb-2.mongodb.czribi.svc.cluster.local:27017" }
      ]
    });
