apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: czribi
spec:
  serviceName: mongodb
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongo
          image: mongo:6.0
          command:
            - mongod
            - "--replSet=rs0"
            - "--bind_ip_all"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    sleep 10
                    echo "Waiting for MongoDB to start..."
                    mongosh --eval "if (rs.status().ok !== 1) { rs.initiate({
                      _id: 'rs0',
                      members: [
                        { _id: 0, host: 'mongodb-0.mongodb.czribi.svc.cluster.local:27017' },
                        { _id: 1, host: 'mongodb-1.mongodb.czribi.svc.cluster.local:27017' },
                        { _id: 2, host: 'mongodb-2.mongodb.czribi.svc.cluster.local:27017' }
                      ]
                    }) }"
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
