apiVersion: apps/v1
kind: Deployment
metadata:
  name: webnodb-deployment
  namespace: czribi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webnodb
  template:
    metadata:
      labels:
        app: webnodb
    spec:
      containers:
      - name: flask-app1
        image: cyrinez/new-flask-app:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m" # 1/10 CPU
            memory: "100Mi" # 100 Mo
          limits:
            cpu: "200m" # 1/5 CPU
            memory: "200Mi" # 200 Mo
---
apiVersion: v1
kind: Service
metadata:
  name: webnodb-service
  namespace: czribi
spec:
  selector:
    app: webnodb
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP
