apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: czribi
spec:
  # ClusterIP: None => headless
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
