apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.mongodb.service.name }}
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
