apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.webnodb.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.webnodb.replicaCount }}
  selector:
    matchLabels:
      app: webnodb
  template:
    metadata:
      labels:
        app: {{ .Values.webnodb.service.name }}
    spec:
      containers:
        - name: webnodb
          image: {{ .Values.webnodb.image }}
          ports:
            - containerPort: {{ .Values.webnodb.service.port }}
          resources:
            requests:
              memory: {{ .Values.webnodb.resources.requests.memory }}
              cpu: {{ .Values.webnodb.resources.requests.cpu }}
            limits:
              memory: {{ .Values.webnodb.resources.limits.memory }}
              cpu: {{ .Values.webnodb.resources.limits.cpu }}
